## Dataframe pandas

In [10]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame
from random import randint

In [3]:
m = np.arange(30).reshape(6,-1)
df = DataFrame(m, columns=list('abcde'))
df

    a   b   c   d   e
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19
4  20  21  22  23  24
5  25  26  27  28  29

In [4]:
df.shape

(6, 5)

In [5]:
df['a']

0     0
1     5
2    10
3    15
4    20
5    25
Name: a, dtype: int32

In [6]:
df.loc[0]

a    0
b    1
c    2
d    3
e    4
Name: 0, dtype: int32

In [7]:
df['e'][5], df.loc[5]['e']

(29, 29)

In [8]:
df2 = df[['a','c','d']]
df2

    a   c   d
0   0   2   3
1   5   7   8
2  10  12  13
3  15  17  18
4  20  22  23
5  25  27  28

In [9]:
type(df2)

pandas.core.frame.DataFrame

In [11]:
d = {letra:[randint(1,30) for _ in range(5)] for letra in "ABCDE"}
df3 = DataFrame(d)
df3

    A   B   C   D   E
0  13  28  27   4  13
1  11  14  11  25  23
2  14   6  12   1  25
3  26  21   6   8   3
4  15  10   7  19  19