## Pandas: conectar con la BD

In [2]:
import sqlite3 as dbapi
import pandas as pd
from pandas import DataFrame
from os.path import isfile
import matplotlib.pyplot as plt

In [3]:
path = "../../BBDD/empresa3.db"

In [4]:
def cargaSQL(path, sql):
    if not isfile(path):
        raise FileNotFoundError(f"No existe el fichero: {path}")
        
    else:
        con = None
        try:
            con = dbapi.connect(path)
            df = pd.read_sql(sql, con)
            return df
        except Exception as e:
            print(e)
        finally:
            if con: con.close()

In [5]:
sql = """select pais, count(idpedido) as cuenta
from pedidos
group by pais
order by 2 desc"""

In [10]:
df = cargaSQL(path, sql)
df.head()

             pais  cuenta
0  Estados Unidos     123
1        Alemania     122
2          Brasil      83
3         Francia      76
4     Reino Unido      55

In [11]:
dfTop5 = df.loc[0:4] # OJO incluye el cuarto
dfTop5.shape

(5, 2)

In [12]:
dfTop5.tail()

             pais  cuenta
0  Estados Unidos     123
1        Alemania     122
2          Brasil      83
3         Francia      76
4     Reino Unido      55

In [ ]:
plt.pie(dfTop5.cuenta, labels=)