## Pruebas con pandas

### Series

In [22]:
import pandas as pd
import numpy as np
from pandas import Series, DataFrame

In [2]:
s1 = Series([1,4,5,6,9])
s2 = Series(np.arange(10))

In [3]:
s1

0    1
1    4
2    5
3    6
4    9
dtype: int64

In [4]:
s3 = Series([1,2,3,4,5], index=list('abcde'))
s3

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [5]:
s3['a'], s3[0], s3[-5]

(1, 1, 1)

In [6]:
s4 = s3[['a','b','d']]
s4

a    1
b    2
d    4
dtype: int64

In [7]:
s4 > 2

a    False
b    False
d     True
dtype: bool

In [8]:
s4 * 10

a    10
b    20
d    40
dtype: int64

In [9]:
s3

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [10]:
s4 = Series([10,20,30,40,50], index=list('aeiou'))
s4

a    10
e    20
i    30
o    40
u    50
dtype: int64

In [14]:
suma = s3 + s4
suma

a    11.0
b     NaN
c     NaN
d     NaN
e    25.0
i     NaN
o     NaN
u     NaN
dtype: float64

In [18]:
suma = s3.add(s4, fill_value=0)
suma

a    11.0
b     2.0
c     3.0
d     4.0
e    25.0
i    30.0
o    40.0
u    50.0
dtype: float64

In [15]:
s3 + s3

a     2
b     4
c     6
d     8
e    10
dtype: int64

In [17]:
s3 < s3

a    False
b    False
c    False
d    False
e    False
dtype: bool

In [19]:
suma[suma > 5]

a    11.0
e    25.0
i    30.0
o    40.0
u    50.0
dtype: float64

In [20]:
suma.isnull()

a    False
b    False
c    False
d    False
e    False
i    False
o    False
u    False
dtype: bool

### Dataframe

In [23]:
df1 = DataFrame(np.arange(25).reshape(5,5))
df1

    0   1   2   3   4
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19
4  20  21  22  23  24

In [25]:
df2 = DataFrame(np.arange(25).reshape(5,5), columns=list('abcde'))
df2

    a   b   c   d   e
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19
4  20  21  22  23  24

In [26]:
# Una columna:
df2['a']

0     0
1     5
2    10
3    15
4    20
Name: a, dtype: int32

In [27]:
df2.a

0     0
1     5
2    10
3    15
4    20
Name: a, dtype: int32

In [28]:
df2.loc[2]

a    10
b    11
c    12
d    13
e    14
Name: 2, dtype: int32

In [29]:
# Celda
df2['e'][4]

24

In [30]:
df2.loc[4]['e']

24

In [32]:
df2[['b','d']]

    b   d
0   1   3
1   6   8
2  11  13
3  16  18
4  21  23