## Pruebas con pandas

### Series

In [1]:
import pandas as pd
import numpy as np
from pandas import Series, DataFrame
from random import randint

In [2]:
s1 = Series([1,4,5,6,9])
s2 = Series(np.arange(10))

In [3]:
s1

0    1
1    4
2    5
3    6
4    9
dtype: int64

In [4]:
s3 = Series([1,2,3,4,5], index=list('abcde'))
s3

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [5]:
s3['a'], s3[0], s3[-5]

(1, 1, 1)

In [6]:
s4 = s3[['a','b','d']]
s4

a    1
b    2
d    4
dtype: int64

In [7]:
s4 > 2

a    False
b    False
d     True
dtype: bool

In [8]:
s4 * 10

a    10
b    20
d    40
dtype: int64

In [9]:
s3

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [10]:
s4 = Series([10,20,30,40,50], index=list('aeiou'))
s4

a    10
e    20
i    30
o    40
u    50
dtype: int64

In [11]:
suma = s3 + s4
suma

a    11.0
b     NaN
c     NaN
d     NaN
e    25.0
i     NaN
o     NaN
u     NaN
dtype: float64

In [12]:
suma = s3.add(s4, fill_value=0)
suma

a    11.0
b     2.0
c     3.0
d     4.0
e    25.0
i    30.0
o    40.0
u    50.0
dtype: float64

In [13]:
s3 + s3

a     2
b     4
c     6
d     8
e    10
dtype: int64

In [14]:
s3 < s3

a    False
b    False
c    False
d    False
e    False
dtype: bool

In [15]:
suma[suma > 5]

a    11.0
e    25.0
i    30.0
o    40.0
u    50.0
dtype: float64

In [16]:
suma.isnull()

a    False
b    False
c    False
d    False
e    False
i    False
o    False
u    False
dtype: bool

### Dataframe

In [17]:
df1 = DataFrame(np.arange(25).reshape(5,5))
df1

    0   1   2   3   4
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19
4  20  21  22  23  24

In [18]:
df2 = DataFrame(np.arange(25).reshape(5,5), columns=list('abcde'))
df2

    a   b   c   d   e
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19
4  20  21  22  23  24

In [19]:
# Una columna:
df2['a']

0     0
1     5
2    10
3    15
4    20
Name: a, dtype: int32

In [20]:
type(df2['a'])

pandas.core.series.Series

In [21]:
df2.a

0     0
1     5
2    10
3    15
4    20
Name: a, dtype: int32

In [22]:
df2.loc[2]

a    10
b    11
c    12
d    13
e    14
Name: 2, dtype: int32

In [23]:
# Celda
df2['e'][4]

24

In [24]:
df2.loc[4]['e']

24

In [25]:
df2[['b','d']]

    b   d
0   1   3
1   6   8
2  11  13
3  16  18
4  21  23

In [26]:
type(df2[['b','d']])

pandas.core.frame.DataFrame

In [27]:
d = {letra:[randint(1,10) for _ in range(8)] for letra in "aeiou"}
for k,L in d.items():
    print(k, L)

a [4, 10, 5, 2, 1, 3, 1, 1]
e [10, 2, 9, 7, 8, 3, 10, 10]
i [3, 2, 6, 9, 8, 1, 7, 5]
o [10, 10, 6, 7, 4, 5, 10, 10]
u [1, 9, 10, 5, 10, 5, 5, 4]

In [28]:
df2 = DataFrame(d)
df2

    a   e  i   o   u
0   4  10  3  10   1
1  10   2  2  10   9
2   5   9  6   6  10
3   2   7  9   7   5
4   1   8  8   4  10
5   3   3  1   5   5
6   1  10  7  10   5
7   1  10  5  10   4

### DataFrame desde ficheros, funciones típicas

In [31]:
path = "../../practicas/avanzado2/pandas/merge/Pedidos.txt"

In [32]:
df = pd.read_csv(path, sep=';')
df

     idpedido cliente  idempleado  idempresa  importe            pais
0       10248   WILMK           5          3    32.38       Finlandia
1       10249   TOMSP           6          1    11.61        Alemania
2       10250   HANAR           4          2    65.83          Brasil
3       10251   VICTE           3          1    41.34         Francia
4       10252   SUPRD           4          2    51.30         Belgica
..        ...     ...         ...        ...      ...             ...
825     11073   PERIC           2          2    24.95          Mexico
826     11074   SIMOB           7          2    18.44       Dinamarca
827     11075   RICSU           8          2     6.19           Suiza
828     11076   BONAP           4          2    38.28         Francia
829     11077   RATTC           1          2     8.53  Estados Unidos

[830 rows x 6 columns]

In [33]:
df.head(3)

   idpedido cliente  idempleado  idempresa  importe       pais
0     10248   WILMK           5          3    32.38  Finlandia
1     10249   TOMSP           6          1    11.61   Alemania
2     10250   HANAR           4          2    65.83     Brasil

In [34]:
df.tail(5)

     idpedido cliente  idempleado  idempresa  importe            pais
825     11073   PERIC           2          2    24.95          Mexico
826     11074   SIMOB           7          2    18.44       Dinamarca
827     11075   RICSU           8          2     6.19           Suiza
828     11076   BONAP           4          2    38.28         Francia
829     11077   RATTC           1          2     8.53  Estados Unidos

In [35]:
df.shape

(830, 6)

In [36]:
filas, cols = df.shape
filas

830

In [37]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 830 entries, 0 to 829
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   idpedido    830 non-null    int64
 1   cliente     830 non-null    object
 2   idempleado  830 non-null    int64
 3   idempresa   830 non-null    int64
 4   importe     830 non-null    float64
 5   pais        830 non-null    object
dtypes: float64(1), int64(3), object(2)
memory usage: 39.0+ KB

In [38]:
df.describe()

           idpedido  idempleado   idempresa      importe
count    830.000000  830.000000  830.000000   830.000000
mean   10662.500000    4.403614    2.008434    78.244205
std      239.744656    2.499648    0.778899   116.779294
min    10248.000000    1.000000    1.000000     0.020000
25%    10455.250000    2.000000    1.000000    13.380000
50%    10662.500000    4.000000    2.000000    41.360000
75%    10869.750000    7.000000    3.000000    91.430000
max    11077.000000    9.000000    3.000000  1007.640000

Crear columnas y operar:

In [40]:
df.head()

   idpedido cliente  idempleado  idempresa  importe       pais
0     10248   WILMK           5          3    32.38  Finlandia
1     10249   TOMSP           6          1    11.61   Alemania
2     10250   HANAR           4          2    65.83     Brasil
3     10251   VICTE           3          1    41.34    Francia
4     10252   SUPRD           4          2    51.30    Belgica

In [41]:
df['porc_iva'] = 21.0

In [42]:
df.head()

   idpedido cliente  idempleado  idempresa  importe       pais  porc_iva
0     10248   WILMK           5          3    32.38  Finlandia      21.0
1     10249   TOMSP           6          1    11.61   Alemania      21.0
2     10250   HANAR           4          2    65.83     Brasil      21.0
3     10251   VICTE           3          1    41.34    Francia      21.0
4     10252   SUPRD           4          2    51.30    Belgica      21.0

In [43]:
df['iva'] = round(df.importe * df.porc_iva / 100, 2)

In [44]:
df['total'] = round(df.iva + df.importe, 2)

In [45]:
df.head()

,idpedido,cliente,idempleado,idempresa,importe,pais,porc_iva,iva,total
0,10248,WILMK,5,3,32.38,Finlandia,21.0,6.80,39.18
1,10249,TOMSP,6,1,11.61,Alemania,21.0,2.44,14.05
2,10250,HANAR,4,2,65.83,Brasil,21.0,13.82,79.65
3,10251,VICTE,3,1,41.34,Francia,21.0,8.68,50.02
4,10252,SUPRD,4,2,51.30,Belgica,21.0,10.77,62.07

In [46]:
df2 = df[['idpedido','cliente','importe','porc_iva','iva','total','pais']]
df2.head()

   idpedido cliente  importe  porc_iva    iva  total       pais
0     10248   WILMK    32.38      21.0   6.80  39.18  Finlandia
1     10249   TOMSP    11.61      21.0   2.44  14.05   Alemania
2     10250   HANAR    65.83      21.0  13.82  79.65     Brasil
3     10251   VICTE    41.34      21.0   8.68  50.02    Francia
4     10252   SUPRD    51.30      21.0  10.77  62.07    Belgica

In [49]:
# Exportar a CSV (con Excel en español)
path_salida = "../../practicas/avanzado2/pandas/merge/csv"
df2.to_csv(path_salida+"/Pedidos.csv", sep=';', index=False, decimal=',')

In [52]:
# Para filtrar filas: Pedidos de Suiza 
dfSuiza = df2[(df2.pais == 'Suiza') & (df2.total > 100.0)]
dfSuiza

     idpedido cliente  importe  porc_iva    iva   total   pais
7       10255   RICSU   148.33      21.0  31.15  179.48  Suiza
171     10419   RICSU   137.35      21.0  28.84  166.19  Suiza
271     10519   CHOPS    91.76      21.0  19.27  111.03  Suiza
418     10666   RICSU   232.42      21.0  48.81  281.23  Suiza
483     10731   CHOPS    96.65      21.0  20.30  116.95  Suiza
503     10751   RICSU   130.79      21.0  27.47  158.26  Suiza
510     10758   RICSU   138.17      21.0  29.02  167.19  Suiza
785     11033   RICSU    84.74      21.0  17.80  102.54  Suiza

In [54]:
np.sum(dfSuiza.total)

1282.87

In [55]:
# Valores únicos de una columna
L = df.pais.unique()
L

array(['Finlandia', 'Alemania', 'Brasil', 'Francia', 'Belgica', 'Suiza',
       'Venezuela', 'Austria', 'Mexico', 'Estados Unidos', 'Suecia',
       'Italia', 'Espanya', 'Reino Unido', 'Irlanda', 'Portugal',
       'Canada', 'Dinamarca', 'Polonia', 'Noruega', 'Argentina'],
      dtype=object)

In [56]:
len(L)

21

Práctica: Exportar los pedidos de cada país a un fichero distinto.

In [58]:
for pais in L:
    
    # Generar la ruta del fichero destino
    path_file = f"../../practicas/avanzado2/pandas/merge/csv/{pais}.xlsx"
    print('Generando fichero: ', path_file)
    
    # Filtrar por países en Pedidos:
    dfPais = df[df.pais==pais]
    
    # Obtener número de filas
    print(dfPais.shape)
    
    # Grabar a Excel:
    dfPais.to_excel(path_file, index=False)
    print()

Generando fichero:  ../../practicas/avanzado2/pandas/merge/csv/Finlandia.xlsx
(23, 9)

Generando fichero:  ../../practicas/avanzado2/pandas/merge/csv/Alemania.xlsx
(122, 9)

Generando fichero:  ../../practicas/avanzado2/pandas/merge/csv/Brasil.xlsx
(83, 9)

Generando fichero:  ../../practicas/avanzado2/pandas/merge/csv/Francia.xlsx
(76, 9)

Generando fichero:  ../../practicas/avanzado2/pandas/merge/csv/Belgica.xlsx
(19, 9)

Generando fichero:  ../../practicas/avanzado2/pandas/merge/csv/Suiza.xlsx
(18, 9)

Generando fichero:  ../../practicas/avanzado2/pandas/merge/csv/Venezuela.xlsx
(46, 9)

Generando fichero:  ../../practicas/avanzado2/pandas/merge/csv/Austria.xlsx
(40, 9)

Generando fichero:  ../../practicas/avanzado2/pandas/merge/csv/Mexico.xlsx
(28, 9)

Generando fichero:  ../../practicas/avanzado2/pandas/merge/csv/Estados Unidos.xlsx
(123, 9)

Generando fichero:  ../../practicas/avanzado2/pandas/merge/csv/Suecia.xlsx
(38, 9)

Generando fichero:  ../../practicas/avanzado2/pandas/merge/csv/Italia.xlsx
(28, 9)

Generando fichero:  ../../practicas/avanzado2/pandas/merge/csv/Espanya.xlsx
(23, 9)

Generando fichero:  ../../practicas/avanzado2/pandas/merge/csv/Reino Unido.xlsx
(55, 9)

Generando fichero:  ../../practicas/avanzado2/pandas/merge/csv/Irlanda.xlsx
(19, 9)

Generando fichero:  ../../practicas/avanzado2/pandas/merge/csv/Portugal.xlsx
(13, 9)

Generando fichero:  ../../practicas/avanzado2/pandas/merge/csv/Canada.xlsx
(30, 9)

Generando fichero:  ../../practicas/avanzado2/pandas/merge/csv/Dinamarca.xlsx
(18, 9)

Generando fichero:  ../../practicas/avanzado2/pandas/merge/csv/Polonia.xlsx
(6, 9)

Generando fichero:  ../../practicas/avanzado2/pandas/merge/csv/Noruega.xlsx
(6, 9)

Generando fichero:  ../../practicas/avanzado2/pandas/merge/csv/Argentina.xlsx
(16, 9)

### Pandas merge

Montar un dataframe fusionando los ficheros de pedidos, empleados y empresas

In [59]:
path = "../../practicas/avanzado2/pandas/merge/"
dfPed = pd.read_csv(path+"Pedidos.txt", sep=';')
dfPed.head()

   idpedido cliente  idempleado  idempresa  importe       pais
0     10248   WILMK           5          3    32.38  Finlandia
1     10249   TOMSP           6          1    11.61   Alemania
2     10250   HANAR           4          2    65.83     Brasil
3     10251   VICTE           3          1    41.34    Francia
4     10252   SUPRD           4          2    51.30    Belgica

In [60]:
dfEmpr = pd.read_csv(path+"Empresas.txt", sep=';')
dfEmpr.head()

   id           empresa
0   1    Speedy Express
1   2    United Package
2   3  Federal Shipping

In [61]:
dfEmpl = pd.read_csv(path+"Empleados.txt", sep=';')
dfEmpl.head()

   id     nombre                     cargo
0   1    Davolio   Representante de ventas
1   2     Fuller  Vicepresidente comercial
2   3  Leverling   Representante de ventas
3   4    Peacock   Representante de ventas
4   5   Buchanan         Gerente de ventas

In [63]:
dfPedEmpr = pd.merge(dfPed, dfEmpr, left_on="idempresa", right_on="id")
dfPedEmpr.head()

,idpedido,cliente,idempleado,idempresa,importe,pais,id,empresa
0,10248,WILMK,5,3,32.38,Finlandia,3,Federal Shipping
1,10255,RICSU,9,3,148.33,Suiza,3,Federal Shipping
2,10257,HILAA,4,3,81.91,Venezuela,3,Federal Shipping
3,10259,CENTC,4,3,3.25,Mexico,3,Federal Shipping
4,10262,RATTC,8,3,48.29,Estados Unidos,3,Federal Shipping

In [64]:
dfPedEmpr.tail()

,idpedido,cliente,idempleado,idempresa,importe,pais,id,empresa
825,11073,PERIC,2,2,24.95,Mexico,2,United Package
826,11074,SIMOB,7,2,18.44,Dinamarca,2,United Package
827,11075,RICSU,8,2,6.19,Suiza,2,United Package
828,11076,BONAP,4,2,38.28,Francia,2,United Package
829,11077,RATTC,1,2,8.53,Estados Unidos,2,United Package

In [65]:
dfTotal = pd.merge(dfPedEmpr, dfEmpl, left_on="idempleado", right_on="id")
dfTotal.head()

,idpedido,cliente,idempleado,idempresa,importe,pais,id_x,empresa,id_y,nombre,cargo
0,10248,WILMK,5,3,32.38,Finlandia,3,Federal Shipping,5,Buchanan,Gerente de ventas
1,10320,WARTH,5,3,34.57,Finlandia,3,Federal Shipping,5,Buchanan,Gerente de ventas
2,10333,WARTH,5,3,0.59,Finlandia,3,Federal Shipping,5,Buchanan,Gerente de ventas
3,10359,SEVES,5,3,288.43,Reino Unido,3,Federal Shipping,5,Buchanan,Gerente de ventas
4,10378,FOLKO,5,3,5.44,Suecia,3,Federal Shipping,5,Buchanan,Gerente de ventas

In [66]:
# Borrar cols:
dfTotal.drop(columns=['idempleado','idempresa','id_x','id_y'], inplace=True)
dfTotal.head()

,idpedido,cliente,importe,pais,empresa,nombre,cargo
0,10248,WILMK,32.38,Finlandia,Federal Shipping,Buchanan,Gerente de ventas
1,10320,WARTH,34.57,Finlandia,Federal Shipping,Buchanan,Gerente de ventas
2,10333,WARTH,0.59,Finlandia,Federal Shipping,Buchanan,Gerente de ventas
3,10359,SEVES,288.43,Reino Unido,Federal Shipping,Buchanan,Gerente de ventas
4,10378,FOLKO,5.44,Suecia,Federal Shipping,Buchanan,Gerente de ventas

In [68]:
dfTotal.rename(columns={"nombre":"empleado"}, inplace=True)
dfTotal.head()

,idpedido,cliente,importe,pais,empresa,empleado,cargo
0,10248,WILMK,32.38,Finlandia,Federal Shipping,Buchanan,Gerente de ventas
1,10320,WARTH,34.57,Finlandia,Federal Shipping,Buchanan,Gerente de ventas
2,10333,WARTH,0.59,Finlandia,Federal Shipping,Buchanan,Gerente de ventas
3,10359,SEVES,288.43,Reino Unido,Federal Shipping,Buchanan,Gerente de ventas
4,10378,FOLKO,5.44,Suecia,Federal Shipping,Buchanan,Gerente de ventas